# Generated by Django 3.0.4 on 2020-03-05 14:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 3, 5, 14, 51, 26, 375913, tzinfo=utc), verbose_name='Date')),
            ],
        ),
    ]
