# Generated by Django 3.0.4 on 2020-03-09 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplesite', '0003_auto_20200309_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialseries',
            name='tut_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='simplesite.TutorialCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 16, 59, 55, 416097, tzinfo=utc), verbose_name='Date'),
        ),
    ]
