# Generated by Django 3.0.4 on 2020-03-09 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simplesite', '0004_auto_20200309_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tut_series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='simplesite.TutorialSeries', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 9, 17, 4, 22, 467372, tzinfo=utc), verbose_name='Date'),
        ),
    ]
